name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - name: Thundra Foresight JS Instrumentation
        uses: thundra-io/thundra-foresight-js-action@v1
        with:
          apikey: 98b7e7a7-5dfc-48d0-871f-c67333b42a9b
          project_id: f5861c97-8575-4435-adad-5d0955e4d52c
          command: npm run test

